version: "3"

services:
  mariadb:
    container_name: "drupal_testing_mariadb"
    image: wodby/mariadb
    container_name: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  php:
    container_name: "drupal_testing_php"
    image: wodby/drupal-php
    environment:
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./:/var/www/html
  nginx:
    container_name: "drupal_testing_nginx"
    image: wodby/nginx
    depends_on:
      - php
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal8
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
